flesh out flow
foundry4/appeal-planning-decision pull request #120
Opened 2020-11-23 13:41 UTC by GoEagles999

## Ticket Number

UCD-IDONTHAVETHIS

## Description of change
Implement new API endpoint to upload incoming files

## Checklist

- [ ] Requires infrastructure changes
- [ ] I have updated the documentation accordingly
- [ ] I have merged commits to avoid fixing things in this PR
- [ ] New features have tests
- [ ] Breaking change (team conversation required)

## Important

Please do not merge from `master` (please only [rebase](https://github.com/foundry4/appeal-planning-decision/wiki/An-intro-to-Git-Rebase)). This keeps the history linear and easier to debug.

2020-11-23 15:19 UTC, MrSimonEmms requested changes
I think this is in the wrong microservice. The file upload should be in the Document Service API. The Appeals Service only ever receives the file ID (or IDs).

There is a requirement to upload the file in Forms Web App, but that's purely a limitation on HTTP Upload and that it needs to go somewhere. As a workflow:
 - Human clicks "upload file" and submit in Forms Web App (FWA)
 - Browser uploads file to FWA
 - FWA send file to Docs Service. This uploads it to persistent storage (in MVP, Azure Blob Storage). It returns an object with the file ID (a UUID) - maybe including metadata, file type, file size, upload datetime.
 - FWA adds this file ID to the Appeal object and tells the Appeals Service API about it

2020-11-23 15:19 UTC, MrSimonEmms commented on appeals-service-api/src/controllers/appeals.js
> +  async uploadFile(req, res) {
Linting

2020-11-23 15:19 UTC, MrSimonEmms commented on appeals-service-api/src/controllers/appeals.js
> +    console.log(req)
Remove `console.log` - there is a beautiful logger in `req.log` (or `./lib/logger` if don't have `req` available)

2020-11-23 15:19 UTC, MrSimonEmms commented on appeals-service-api/src/routes/appeals.js
> +routes
Linting

2020-11-23 15:19 UTC, MrSimonEmms commented on appeals-service-api/src/routes/appeals.js
> +  .post(appealsController.uploadFile)
The appeals service has no knowledge of uploading - this should be done in the Document Service API

2020-11-23 15:19 UTC, MrSimonEmms commented
@GoEagles999 Can you also find the ticket number in Jira and update the PR description?

2020-11-24 08:51 UTC, a6software commented
> I think this is in the wrong microservice. The file upload should be in the Document Service API. The Appeals Service only ever receives the file ID (or IDs).
> 
> There is a requirement to upload the file in Forms Web App, but that's purely a limitation on HTTP Upload and that it needs to go somewhere. As a workflow:
> 
> * Human clicks "upload file" and submit in Forms Web App (FWA)
> * Browser uploads file to FWA
> * FWA send file to Docs Service. This uploads it to persistent storage (in MVP, Azure Blob Storage). It returns an object with the file ID (a UUID) - maybe including metadata, file type, file size, upload datetime.
> * FWA adds this file ID to the Appeal object and tells the Appeals Service API about it

I would be grateful if we could return the metadata along with the id. At the minimum, for presentation purposes, we need a filename (ideally the original filename). Thanks!

2020-12-03 10:37 UTC, MrSimonEmms requested changes
You need to configure your IDE to use Prettier and EditorConfig as your changes break linting `npm run lint`.

Also, please figure out why the document service tests are being run in GitHub Actions

2020-12-03 10:37 UTC, MrSimonEmms commented on document-service-api/src/routes/index.js
> +const strategy = multer.diskStorage({
For consistency across packages, I would prefer the `express-file-upload` approach as used in forms-web-app. Also, I don't think that the file upload work should be in the router - I think this should be in the controller and the router merely declares the URL and invokes the controller

2020-12-03 10:37 UTC, MrSimonEmms commented on document-service-api/src/lib/config.js
> +  AZURE_BLOB_STORAGE_CONNECTION_STRING: process.env.AZURE_BLOB_STORAGE_CONNECTION_STRING,
I don't like the capitalised keys in the config. I would also suggest putting it inside an object for consistency. Something like:

```
blobStorage: {
  connection: process.env.AZURE_BLOB_STORAGE_CONNECTION_STRING
}
```

2020-12-03 10:37 UTC, MrSimonEmms commented on document-service-api/src/controllers/documentWriter.js
> +module.exports = DocumentWriter;
Add new line at end of file.

Ensure you have [EditorConfig](https://editorconfig.org/) installed in your IDE and this will be done for you

2020-12-03 10:37 UTC, MrSimonEmms commented on document-service-api/src/controllers/documentReader.js
> +module.exports = DocumentReader;
Newline needed

2020-12-10 09:29 UTC, MrSimonEmms requested changes
Please fix CI/CD issues

2020-12-10 09:29 UTC, MrSimonEmms commented on document-service-api/src/lib/config.js
> +    maxFileSizeInBytes: 50 * ONE_MEGABYTE
This should be `maxFileSizeInBytes: Number(process.env.MAX_FILE_SIZE_IN_BYTES)` - the application should neither know nor care of the number as that's a deployment thing

2020-12-14 15:34 UTC, MrSimonEmms commented
Superseded by #201

2020-12-14 15:34 UTC, closed without merging