fix(deadline-date): date formatting added
foundry4/appeal-planning-decision pull request #46
Opened 2020-11-02 16:57 UTC by mmuchlinski

Description of PR...

## Changes

- Item 1
- Item 2

## PR Template Checklist

- [ ] Grammar
- [ ] Spelling
- [ ] Clarity

Fixes #85, Fixes #22, Fixes username/repo#123
Connects #123

2020-11-02 17:14 UTC, jmorgan74 submitted a review, later dismissed
👍

2020-11-02 19:08 UTC, MrSimonEmms requested changes
Root level changes that I'm not expecting have happened

2020-11-02 19:08 UTC, MrSimonEmms commented on package.json
> -  "dependencies": {},
Please restore this line

2020-11-02 19:08 UTC, MrSimonEmms commented on package-lock.json
> +    "a-sync-waterfall": {
I wouldn't have expected any changes in this file - can you restore the original file and then run `make uninstall` and then `make install`. If it does make any changes, that's fine but please confirm this

2020-11-02 19:21 UTC, MrSimonEmms commented
Can we also have a linear-commit history? It would be better to rebase this commit to the second "remove" didn't exist (it also breaks things because it's required in semantic-release)

Also, please don't make manual changes in package-lock.json - this is an autogenerated file.

![image](https://user-images.githubusercontent.com/275848/97909637-7734e600-1d40-11eb-99e5-d7dd9e73f583.png)

2020-11-03 11:43 UTC, jmorgan74 commented on package.json
> -  "dependencies": {},
done

2020-11-03 12:05 UTC, jmorgan74 approved these changes

2020-11-03 12:08 UTC, MrSimonEmms approved these changes

2020-11-03 12:11 UTC, MrSimonEmms approved these changes

2020-11-03 12:14 UTC, merged